name: Feature request
description: Propose a new capability or improvement.
title: "feature: "
labels:
  - type:feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user/job-to-be-done is not served today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior and UX.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - p0
        - p1
        - p2
        - p3
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define testable outcomes.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks / trade-offs
